package com.kuangkee.search.pojo;

public class Account {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.id
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.version
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    private Long version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.phone
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.tagid_list
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    private String tagidList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.province
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.sex
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.subscribe
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    private Integer subscribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.nickname
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.groupid
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    private String groupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.language
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    private String language;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.subscribe_time
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    private Long subscribeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.openid
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.city
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.remark
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.unionid
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    private String unionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.country
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.headimgurl
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    private String headimgurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.id
     *
     * @return the value of t_account.id
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.id
     *
     * @param id the value for t_account.id
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.version
     *
     * @return the value of t_account.version
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.version
     *
     * @param version the value for t_account.version
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.phone
     *
     * @return the value of t_account.phone
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.phone
     *
     * @param phone the value for t_account.phone
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.tagid_list
     *
     * @return the value of t_account.tagid_list
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    public String getTagidList() {
        return tagidList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.tagid_list
     *
     * @param tagidList the value for t_account.tagid_list
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    public void setTagidList(String tagidList) {
        this.tagidList = tagidList == null ? null : tagidList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.province
     *
     * @return the value of t_account.province
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.province
     *
     * @param province the value for t_account.province
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.sex
     *
     * @return the value of t_account.sex
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.sex
     *
     * @param sex the value for t_account.sex
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.subscribe
     *
     * @return the value of t_account.subscribe
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    public Integer getSubscribe() {
        return subscribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.subscribe
     *
     * @param subscribe the value for t_account.subscribe
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    public void setSubscribe(Integer subscribe) {
        this.subscribe = subscribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.nickname
     *
     * @return the value of t_account.nickname
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.nickname
     *
     * @param nickname the value for t_account.nickname
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.groupid
     *
     * @return the value of t_account.groupid
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    public String getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.groupid
     *
     * @param groupid the value for t_account.groupid
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    public void setGroupid(String groupid) {
        this.groupid = groupid == null ? null : groupid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.language
     *
     * @return the value of t_account.language
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.language
     *
     * @param language the value for t_account.language
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.subscribe_time
     *
     * @return the value of t_account.subscribe_time
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    public Long getSubscribeTime() {
        return subscribeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.subscribe_time
     *
     * @param subscribeTime the value for t_account.subscribe_time
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    public void setSubscribeTime(Long subscribeTime) {
        this.subscribeTime = subscribeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.openid
     *
     * @return the value of t_account.openid
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.openid
     *
     * @param openid the value for t_account.openid
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.city
     *
     * @return the value of t_account.city
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.city
     *
     * @param city the value for t_account.city
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.remark
     *
     * @return the value of t_account.remark
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.remark
     *
     * @param remark the value for t_account.remark
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.unionid
     *
     * @return the value of t_account.unionid
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    public String getUnionid() {
        return unionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.unionid
     *
     * @param unionid the value for t_account.unionid
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    public void setUnionid(String unionid) {
        this.unionid = unionid == null ? null : unionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.country
     *
     * @return the value of t_account.country
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.country
     *
     * @param country the value for t_account.country
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.headimgurl
     *
     * @return the value of t_account.headimgurl
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    public String getHeadimgurl() {
        return headimgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.headimgurl
     *
     * @param headimgurl the value for t_account.headimgurl
     *
     * @mbggenerated Sun Feb 25 09:52:42 CST 2018
     */
    public void setHeadimgurl(String headimgurl) {
        this.headimgurl = headimgurl == null ? null : headimgurl.trim();
    }
}