package com.kuangkee.search.pojo;

import java.util.Date;

public class Article {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.article_id
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    private Long articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.brand_id
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    private String brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.brand_name
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    private String brandName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.error_code
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    private String errorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.title
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.sub_title
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    private String subTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.img_search_small
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    private String imgSearchSmall;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.img_content_big
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    private String imgContentBig;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.img_content_small
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    private String imgContentSmall;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.source_url
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    private String sourceUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.is_searchable
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    private String isSearchable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.creater
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.creater_desc
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    private String createrDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.read_times
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    private String readTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.create_time
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.update_time
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.content
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.article_id
     *
     * @return the value of tb_article.article_id
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.article_id
     *
     * @param articleId the value for tb_article.article_id
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.brand_id
     *
     * @return the value of tb_article.brand_id
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    public String getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.brand_id
     *
     * @param brandId the value for tb_article.brand_id
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    public void setBrandId(String brandId) {
        this.brandId = brandId == null ? null : brandId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.brand_name
     *
     * @return the value of tb_article.brand_name
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.brand_name
     *
     * @param brandName the value for tb_article.brand_name
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.error_code
     *
     * @return the value of tb_article.error_code
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    public String getErrorCode() {
        return errorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.error_code
     *
     * @param errorCode the value for tb_article.error_code
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    public void setErrorCode(String errorCode) {
        this.errorCode = errorCode == null ? null : errorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.title
     *
     * @return the value of tb_article.title
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.title
     *
     * @param title the value for tb_article.title
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.sub_title
     *
     * @return the value of tb_article.sub_title
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    public String getSubTitle() {
        return subTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.sub_title
     *
     * @param subTitle the value for tb_article.sub_title
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    public void setSubTitle(String subTitle) {
        this.subTitle = subTitle == null ? null : subTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.img_search_small
     *
     * @return the value of tb_article.img_search_small
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    public String getImgSearchSmall() {
        return imgSearchSmall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.img_search_small
     *
     * @param imgSearchSmall the value for tb_article.img_search_small
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    public void setImgSearchSmall(String imgSearchSmall) {
        this.imgSearchSmall = imgSearchSmall == null ? null : imgSearchSmall.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.img_content_big
     *
     * @return the value of tb_article.img_content_big
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    public String getImgContentBig() {
        return imgContentBig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.img_content_big
     *
     * @param imgContentBig the value for tb_article.img_content_big
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    public void setImgContentBig(String imgContentBig) {
        this.imgContentBig = imgContentBig == null ? null : imgContentBig.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.img_content_small
     *
     * @return the value of tb_article.img_content_small
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    public String getImgContentSmall() {
        return imgContentSmall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.img_content_small
     *
     * @param imgContentSmall the value for tb_article.img_content_small
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    public void setImgContentSmall(String imgContentSmall) {
        this.imgContentSmall = imgContentSmall == null ? null : imgContentSmall.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.source_url
     *
     * @return the value of tb_article.source_url
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    public String getSourceUrl() {
        return sourceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.source_url
     *
     * @param sourceUrl the value for tb_article.source_url
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    public void setSourceUrl(String sourceUrl) {
        this.sourceUrl = sourceUrl == null ? null : sourceUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.is_searchable
     *
     * @return the value of tb_article.is_searchable
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    public String getIsSearchable() {
        return isSearchable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.is_searchable
     *
     * @param isSearchable the value for tb_article.is_searchable
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    public void setIsSearchable(String isSearchable) {
        this.isSearchable = isSearchable == null ? null : isSearchable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.creater
     *
     * @return the value of tb_article.creater
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.creater
     *
     * @param creater the value for tb_article.creater
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.creater_desc
     *
     * @return the value of tb_article.creater_desc
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    public String getCreaterDesc() {
        return createrDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.creater_desc
     *
     * @param createrDesc the value for tb_article.creater_desc
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    public void setCreaterDesc(String createrDesc) {
        this.createrDesc = createrDesc == null ? null : createrDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.read_times
     *
     * @return the value of tb_article.read_times
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    public String getReadTimes() {
        return readTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.read_times
     *
     * @param readTimes the value for tb_article.read_times
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    public void setReadTimes(String readTimes) {
        this.readTimes = readTimes == null ? null : readTimes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.create_time
     *
     * @return the value of tb_article.create_time
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.create_time
     *
     * @param createTime the value for tb_article.create_time
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.update_time
     *
     * @return the value of tb_article.update_time
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.update_time
     *
     * @param updateTime the value for tb_article.update_time
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.content
     *
     * @return the value of tb_article.content
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.content
     *
     * @param content the value for tb_article.content
     *
     * @mbggenerated Thu Mar 01 14:51:40 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

	@Override
	public String toString() {
		return "Article [articleId=" + articleId + ", brandId=" + brandId + ", brandName=" + brandName + ", errorCode="
				+ errorCode + ", title=" + title + ", subTitle=" + subTitle + ", imgSearchSmall=" + imgSearchSmall
				+ ", imgContentBig=" + imgContentBig + ", imgContentSmall=" + imgContentSmall + ", sourceUrl="
				+ sourceUrl + ", isSearchable=" + isSearchable + ", creater=" + creater + ", createrDesc=" + createrDesc
				+ ", readTimes=" + readTimes + ", createTime=" + createTime + ", updateTime=" + updateTime
				+ ", content=" + content + "]";
	}
    
    
}