package com.kuangkee.search.pojo;

public class Brand {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_brand.id
     *
     * @mbggenerated Wed Feb 28 15:36:38 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_brand.version
     *
     * @mbggenerated Wed Feb 28 15:36:38 CST 2018
     */
    private Long version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_brand.orders
     *
     * @mbggenerated Wed Feb 28 15:36:38 CST 2018
     */
    private Integer orders;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_brand.name
     *
     * @mbggenerated Wed Feb 28 15:36:38 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_brand.id
     *
     * @return the value of t_brand.id
     *
     * @mbggenerated Wed Feb 28 15:36:38 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_brand.id
     *
     * @param id the value for t_brand.id
     *
     * @mbggenerated Wed Feb 28 15:36:38 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_brand.version
     *
     * @return the value of t_brand.version
     *
     * @mbggenerated Wed Feb 28 15:36:38 CST 2018
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_brand.version
     *
     * @param version the value for t_brand.version
     *
     * @mbggenerated Wed Feb 28 15:36:38 CST 2018
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_brand.orders
     *
     * @return the value of t_brand.orders
     *
     * @mbggenerated Wed Feb 28 15:36:38 CST 2018
     */
    public Integer getOrders() {
        return orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_brand.orders
     *
     * @param orders the value for t_brand.orders
     *
     * @mbggenerated Wed Feb 28 15:36:38 CST 2018
     */
    public void setOrders(Integer orders) {
        this.orders = orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_brand.name
     *
     * @return the value of t_brand.name
     *
     * @mbggenerated Wed Feb 28 15:36:38 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_brand.name
     *
     * @param name the value for t_brand.name
     *
     * @mbggenerated Wed Feb 28 15:36:38 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}