package com.kuangkee.search.pojo;

public class BrandVolvo implements Comparable<BrandVolvo>{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_brand_volvo.id
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_brand_volvo.partId
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    private String partid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_brand_volvo.brand_id
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    private String brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_brand_volvo.brand_name
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    private String brandName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_brand_volvo.error_code
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    private String errorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_brand_volvo.title
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_brand_volvo.id
     *
     * @return the value of tb_brand_volvo.id
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_brand_volvo.id
     *
     * @param id the value for tb_brand_volvo.id
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_brand_volvo.partId
     *
     * @return the value of tb_brand_volvo.partId
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    public String getPartid() {
        return partid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_brand_volvo.partId
     *
     * @param partid the value for tb_brand_volvo.partId
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    public void setPartid(String partid) {
        this.partid = partid == null ? null : partid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_brand_volvo.brand_id
     *
     * @return the value of tb_brand_volvo.brand_id
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    public String getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_brand_volvo.brand_id
     *
     * @param brandId the value for tb_brand_volvo.brand_id
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    public void setBrandId(String brandId) {
        this.brandId = brandId == null ? null : brandId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_brand_volvo.brand_name
     *
     * @return the value of tb_brand_volvo.brand_name
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_brand_volvo.brand_name
     *
     * @param brandName the value for tb_brand_volvo.brand_name
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_brand_volvo.error_code
     *
     * @return the value of tb_brand_volvo.error_code
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    public String getErrorCode() {
        return errorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_brand_volvo.error_code
     *
     * @param errorCode the value for tb_brand_volvo.error_code
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    public void setErrorCode(String errorCode) {
        this.errorCode = errorCode == null ? null : errorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_brand_volvo.title
     *
     * @return the value of tb_brand_volvo.title
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_brand_volvo.title
     *
     * @param title the value for tb_brand_volvo.title
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

	@Override
	public String toString() {
		return "BrandVolvo [id=" + id + ", partid=" + partid + ", brandId=" + brandId + ", brandName=" + brandName
				+ ", errorCode=" + errorCode + ", title=" + title + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((brandId == null) ? 0 : brandId.hashCode());
		result = prime * result + ((brandName == null) ? 0 : brandName.hashCode());
		result = prime * result + ((errorCode == null) ? 0 : errorCode.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((partid == null) ? 0 : partid.hashCode());
		result = prime * result + ((title == null) ? 0 : title.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		BrandVolvo other = (BrandVolvo) obj;
		if (brandId == null) {
			if (other.brandId != null)
				return false;
		} else if (!brandId.equals(other.brandId))
			return false;
		if (brandName == null) {
			if (other.brandName != null)
				return false;
		} else if (!brandName.equals(other.brandName))
			return false;
		if (errorCode == null) {
			if (other.errorCode != null)
				return false;
		} else if (!errorCode.equals(other.errorCode))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (partid == null) {
			if (other.partid != null)
				return false;
		} else if (!partid.equals(other.partid))
			return false;
		if (title == null) {
			if (other.title != null)
				return false;
		} else if (!title.equals(other.title))
			return false;
		return true;
	}

	@Override
	public int compareTo(BrandVolvo o) {
		return Integer.parseInt(this.getPartid())-Integer.parseInt(o.getPartid());
	}

}