package com.kuangkee.search.pojo;

public class BrandVolvo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_brand_volvo.id
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_brand_volvo.partId
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    private String partid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_brand_volvo.brand_id
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    private String brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_brand_volvo.brand_name
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    private String brandName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_brand_volvo.error_code
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    private String errorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_brand_volvo.title
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_brand_volvo.id
     *
     * @return the value of tb_brand_volvo.id
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_brand_volvo.id
     *
     * @param id the value for tb_brand_volvo.id
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_brand_volvo.partId
     *
     * @return the value of tb_brand_volvo.partId
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    public String getPartid() {
        return partid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_brand_volvo.partId
     *
     * @param partid the value for tb_brand_volvo.partId
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    public void setPartid(String partid) {
        this.partid = partid == null ? null : partid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_brand_volvo.brand_id
     *
     * @return the value of tb_brand_volvo.brand_id
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    public String getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_brand_volvo.brand_id
     *
     * @param brandId the value for tb_brand_volvo.brand_id
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    public void setBrandId(String brandId) {
        this.brandId = brandId == null ? null : brandId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_brand_volvo.brand_name
     *
     * @return the value of tb_brand_volvo.brand_name
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_brand_volvo.brand_name
     *
     * @param brandName the value for tb_brand_volvo.brand_name
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_brand_volvo.error_code
     *
     * @return the value of tb_brand_volvo.error_code
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    public String getErrorCode() {
        return errorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_brand_volvo.error_code
     *
     * @param errorCode the value for tb_brand_volvo.error_code
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    public void setErrorCode(String errorCode) {
        this.errorCode = errorCode == null ? null : errorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_brand_volvo.title
     *
     * @return the value of tb_brand_volvo.title
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_brand_volvo.title
     *
     * @param title the value for tb_brand_volvo.title
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }
}