package com.kuangkee.search.pojo;

public class ExpertBrands {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert_brands.expert_brands_id
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    private Long expertBrandsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert_brands.brand_id
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    private Long brandId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert_brands.expert_brands_id
     *
     * @return the value of t_expert_brands.expert_brands_id
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    public Long getExpertBrandsId() {
        return expertBrandsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert_brands.expert_brands_id
     *
     * @param expertBrandsId the value for t_expert_brands.expert_brands_id
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    public void setExpertBrandsId(Long expertBrandsId) {
        this.expertBrandsId = expertBrandsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert_brands.brand_id
     *
     * @return the value of t_expert_brands.brand_id
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    public Long getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert_brands.brand_id
     *
     * @param brandId the value for t_expert_brands.brand_id
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    public void setBrandId(Long brandId) {
        this.brandId = brandId;
    }
}