package com.kuangkee.search.mapper.generate;

import com.kuangkee.search.pojo.BrandVolvo;
import com.kuangkee.search.pojo.BrandVolvoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BrandVolvoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand_volvo
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    int countByExample(BrandVolvoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand_volvo
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    int deleteByExample(BrandVolvoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand_volvo
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    int insert(BrandVolvo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand_volvo
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    int insertSelective(BrandVolvo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand_volvo
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    List<BrandVolvo> selectByExample(BrandVolvoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand_volvo
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    int updateByExampleSelective(@Param("record") BrandVolvo record, @Param("example") BrandVolvoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand_volvo
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    int updateByExample(@Param("record") BrandVolvo record, @Param("example") BrandVolvoExample example);
}