package com.kuangkee.search.mapper.generate;

import com.kuangkee.search.pojo.BrandCat;
import com.kuangkee.search.pojo.BrandCatExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BrandCatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand_cat
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    int countByExample(BrandCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand_cat
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    int deleteByExample(BrandCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand_cat
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    int insert(BrandCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand_cat
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    int insertSelective(BrandCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand_cat
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    List<BrandCat> selectByExample(BrandCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand_cat
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    int updateByExampleSelective(@Param("record") BrandCat record, @Param("example") BrandCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand_cat
     *
     * @mbggenerated Thu Mar 22 16:28:25 CST 2018
     */
    int updateByExample(@Param("record") BrandCat record, @Param("example") BrandCatExample example);
}