package com.kuangkee.search.mapper.generate;

import com.kuangkee.search.pojo.ExpertBrands;
import com.kuangkee.search.pojo.ExpertBrandsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExpertBrandsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_brands
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    int countByExample(ExpertBrandsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_brands
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    int deleteByExample(ExpertBrandsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_brands
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    int insert(ExpertBrands record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_brands
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    int insertSelective(ExpertBrands record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_brands
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    List<ExpertBrands> selectByExample(ExpertBrandsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_brands
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    int updateByExampleSelective(@Param("record") ExpertBrands record, @Param("example") ExpertBrandsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_brands
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    int updateByExample(@Param("record") ExpertBrands record, @Param("example") ExpertBrandsExample example);
}