package com.kuangkee.search.mapper.generate;

import com.kuangkee.search.pojo.Expert;
import com.kuangkee.search.pojo.ExpertExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExpertMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    int countByExample(ExpertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    int deleteByExample(ExpertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    int insert(Expert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    int insertSelective(Expert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    List<Expert> selectByExampleWithBLOBs(ExpertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    List<Expert> selectByExample(ExpertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    Expert selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    int updateByExampleSelective(@Param("record") Expert record, @Param("example") ExpertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Expert record, @Param("example") ExpertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    int updateByExample(@Param("record") Expert record, @Param("example") ExpertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    int updateByPrimaryKeySelective(Expert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Expert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    int updateByPrimaryKey(Expert record);
}