package com.kuangkee.search.pojo.ext ;

import java.util.Date;

public class ExpertExt {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert.id
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert.version
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    private Long version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert.phone
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert.address
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert.agency_shop_name
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    private String agencyShopName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert.curr_status
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    private Integer currStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert.name
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert.wechat
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    private String wechat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert.update_date
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert.agency_shop
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    private Boolean agencyShop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert.create_date
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert.lat
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    private String lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert.lng
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    private String lng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert.price
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert.cousult_times
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    private Integer cousultTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert.info
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    private String info;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert.id
     *
     * @return the value of t_expert.id
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert.id
     *
     * @param id the value for t_expert.id
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert.version
     *
     * @return the value of t_expert.version
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert.version
     *
     * @param version the value for t_expert.version
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert.phone
     *
     * @return the value of t_expert.phone
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert.phone
     *
     * @param phone the value for t_expert.phone
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert.address
     *
     * @return the value of t_expert.address
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert.address
     *
     * @param address the value for t_expert.address
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert.agency_shop_name
     *
     * @return the value of t_expert.agency_shop_name
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    public String getAgencyShopName() {
        return agencyShopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert.agency_shop_name
     *
     * @param agencyShopName the value for t_expert.agency_shop_name
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    public void setAgencyShopName(String agencyShopName) {
        this.agencyShopName = agencyShopName == null ? null : agencyShopName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert.curr_status
     *
     * @return the value of t_expert.curr_status
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    public Integer getCurrStatus() {
        return currStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert.curr_status
     *
     * @param currStatus the value for t_expert.curr_status
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    public void setCurrStatus(Integer currStatus) {
        this.currStatus = currStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert.name
     *
     * @return the value of t_expert.name
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert.name
     *
     * @param name the value for t_expert.name
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert.wechat
     *
     * @return the value of t_expert.wechat
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert.wechat
     *
     * @param wechat the value for t_expert.wechat
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    public void setWechat(String wechat) {
        this.wechat = wechat == null ? null : wechat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert.update_date
     *
     * @return the value of t_expert.update_date
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert.update_date
     *
     * @param updateDate the value for t_expert.update_date
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert.agency_shop
     *
     * @return the value of t_expert.agency_shop
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    public Boolean getAgencyShop() {
        return agencyShop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert.agency_shop
     *
     * @param agencyShop the value for t_expert.agency_shop
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    public void setAgencyShop(Boolean agencyShop) {
        this.agencyShop = agencyShop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert.create_date
     *
     * @return the value of t_expert.create_date
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert.create_date
     *
     * @param createDate the value for t_expert.create_date
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert.lat
     *
     * @return the value of t_expert.lat
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert.lat
     *
     * @param lat the value for t_expert.lat
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    public void setLat(String lat) {
        this.lat = lat == null ? null : lat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert.lng
     *
     * @return the value of t_expert.lng
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    public String getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert.lng
     *
     * @param lng the value for t_expert.lng
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    public void setLng(String lng) {
        this.lng = lng == null ? null : lng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert.price
     *
     * @return the value of t_expert.price
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert.price
     *
     * @param price the value for t_expert.price
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert.cousult_times
     *
     * @return the value of t_expert.cousult_times
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    public Integer getCousultTimes() {
        return cousultTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert.cousult_times
     *
     * @param cousultTimes the value for t_expert.cousult_times
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    public void setCousultTimes(Integer cousultTimes) {
        this.cousultTimes = cousultTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert.info
     *
     * @return the value of t_expert.info
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert.info
     *
     * @param info the value for t_expert.info
     *
     * @mbggenerated Sat Mar 03 09:47:53 CST 2018
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }
}